apiVersion: v1
kind: ConfigMap
metadata:
  name: opentelemetry-collector-config
  namespace: observability
data:
  collector.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317

    processors:
      batch: {}

    exporters:
      otlp/jaeger:
        endpoint: jaeger-collector.observability.svc.cluster.local:4317
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/jaeger]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentelemetry-collector
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opentelemetry-collector
  template:
    metadata:
      labels:
        app: opentelemetry-collector
    spec:
      containers:
      - name: otelcol
        image: otel/opentelemetry-collector-contrib:0.147.0
        args: ["--config=/conf/collector.yaml"]
        ports:
        - name: grpc-otlp
          containerPort: 4317
        volumeMounts:
        - name: conf
          mountPath: /conf
      volumes:
      - name: conf
        configMap:
          name: opentelemetry-collector-config
---
apiVersion: v1
kind: Service
metadata:
  name: opentelemetry-collector
  namespace: observability
spec:
  selector:
    app: opentelemetry-collector
  ports:
  - name: grpc-otlp
    port: 4317
    targetPort: 4317
